"""followers

Revision ID: 425781cee6b7
Revises: b9ebde2f767e
Create Date: 2020-11-16 20:34:32.775015

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '425781cee6b7'
down_revision = 'b9ebde2f767e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
