"""add language to posts

Revision ID: 653e2880a7c8
Revises: 425781cee6b7
Create Date: 2020-12-17 10:15:44.554863

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '653e2880a7c8'
down_revision = '425781cee6b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('language', sa.String(length=5), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'language')
    # ### end Alembic commands ###
